swagger: '2.0'
info:
  version: 1.0.0
  title: Covid API documentation
  description: This is an API



tags:
  - name: sessions
    description: 'to sessions'
  - name: users
    description: 'to clients'
  - name: Volunteers
    description: 'to volunteers'
  - name: Help Request
    description: 'to help request'
    
paths:
  /sessions:
    post:
      tags:
        - sessions
      description: 'Send a user information to the API'
      parameters:
        - name: sessions
          in: body
          required: true
          description: 'Sessions information'
          schema:
            $ref: '#/definitions/SessionData'
            
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/SessionResponse200'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/SessionResponse401'

  /users:
  
    get:
      tags:
        - users
      description: 'Return a list of all users registered in the database'
      parameters:
        - name: user
          type: string
          in: query
          description: 'Filter by names.<br><b>Example:</b>
                        `?name=Daniel`'

      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Response200'
            
    post:
      tags:
        - users
      description: 'Send user information to API'
      parameters:
        - name: users
          in: body
          required: true
          description: 'Users information'
          schema:
            $ref: '#/definitions/UsersData'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/UsersData'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/ValidationFails'


  /volunteers:
    get:
      tags:
        - Volunteers
      description: "Return a list of volunteers"
      
      responses:
        '200':
          description: OK
    post:
      tags:
        - Volunteers
      description: "You can create a volunteer"
      
      responses:
        '200':
          description: OK

  /help:
    get:
      tags:
        - Help Request
      description: "Return a list of help alerts"
      
      responses:
        '200':
          description: OK
    post:
      tags:
        - Help Request
      description: "You can create an Help request"
      
      responses:
        '200':
          description: OK


definitions:

  SessionData:
    required:
      - email
      - password
    type: object
    properties:
      email:
        type: string
        example: "joão@gmail.com"
      
      password:
        type: string
        example: '123456'
      
  UsersData:
    required:
      - name
      - email
      - password
    type: object
    properties:
      name:
        type: string
        example: 'João José'
      email:
        type: string
        example: 'joão@gmail.com'
      whatsapp:
        type: string
        example: '6199999999'
      password:
        type: string
        example: '123456'
      address:
        type: string
        example: '72705010'
      birth_date:
        type: string
        example: '01/01/2001'
      link_unb:
        type: string
        example: 'Discente'
      risk_group:
        type: string
        example: 'Asma'
      user_location:
        type: string
        example: '-15.7757876:-48.077829'


  SessionResponse200:
    type: object
    properties:
      user:
        type: object
        properties:
          id:
            type: integer
            example: 1
          name:
            type: string
            example: João José
          email:
            type: string
            example: joao@gmail.com
      token:
        type: string
        example: "eyJhbGciOiJMpLIC0B5UMYudjNNR3KeDCI0XpNY"

  SessionResponse401:
    type: object
    properties:
      error:
        type: string
        example: "Password does not match"
        
  
        
  ValidationFails:
    type: object
    properties:
      error:
        type: string
        example: "Validation fails"
        
        
  Response200:
    type: object
    properties:
      code:
        type: integer
        example: 200
      message:
        type: string
        example: 'Success'
        
  HelpRequest:
    type: object
    properties:
      name:
        type: string
        example: "Daniel Prado"
      sintoms:
        type: string
        example: "Tosse seca"
      whatsapp:
        type: string
        example: "6155555555"

